config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :foods
  resources :moods
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :foods

  def self.search(search)
    if search
      where("name LIKE :search", search: "#{search}")
    else
      where(nil)
    end
  end
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :category
  belongs_to :user
  belongs_to :type

  def self.search(search)
    if search
      where("type_id LIKE :search", search: "#{search}")
    else
      where(nil)
    end
  end
end

app/models/mood.rb
class Mood < ApplicationRecord
  belongs_to :user
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :foods

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :user_name, :presence => true
  validates :date_of_birth, :presence => true

  has_many :foods
  has_many :moods
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me, :user_name, :date_of_birth, :gender) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :remember_me, :user_name, :date_of_birth, :gender) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  before_action :authenticate_user!
  helper_method :sort_column, :sort_direction

  def index
    # @foods = Food.search(params[:search])
    if @category = Category.search(params[:search]).first
      @foods = Food.where(category_id: @category.id).order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    else
      @foods = Food.order(sort_column + " " + sort_direction).paginate(:per_page => 10, :page => params[:page])
    end
    # @foods = Food.order(sort_column + " " + sort_direction)
  end

  def show
    @food = Food.find(params[:id])
  end

  def edit
    @food = Food.find(params[:id])
  end

  def new
    @food = Food.new
    @categories = Category.all
    @types = Type.all
  end

  def create
    @categories = Category.all
    @types = Type.all
    @food = current_user.foods.new(food_params)
    if @food.save
      flash[:notice] = "Food saved successfully"
      redirect_to new_mood_path
    else
      flash[:alert] = "Food failed to save"
      render :new
    end
  end

  def update
    @food = Food.find(params[:id])
    if @food.update(food_params)
      flash[:notice] = "Food updated"
      redirect_to food_path(@food)
    else
      flash[:alert] = "Food update failed"
      redirect_to food_path(@food)
    end
  end

  def destroy
    @food = Food.find(params[:id])
    if @food.delete
      flash[:notice] = "Food deleted"
      redirect_to foods_path
    else
      flash[:alert] = "Food failed to delete"
    end
  end
  private

  def sort_column
    Food.column_names.include?(params[:sort]) ? params[:sort] : "time_consumed"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def food_params
    params.require(:food).permit(:category_id, :type_id, :time_consumed)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :authenticate_user!
  def index
    @moods = Mood.order(:time)
  end
  def show
    @mood = Mood.find(params[:id])
  end
  def edit
    @mood = Mood.find(params[:id])
  end
  def new
    @mood = Mood.new
  end
  def create
    @mood = current_user.moods.new(mood_params)
    if @mood.save
      flash[:notice] = "Mood saved successfully"
      redirect_to root_path
    else
      flash[:alert] = "Mood failed to save"
      render :new
    end
  end
  def update
    @mood = Mood.find(params[:id])
    if @mood.update(mood_params)
      flash[:notice] = "Mood updated"
      redirect_to mood_path(@mood)
    else
      flash[:alert] = "Mood update failed"
      redirect_to mood_path(@mood)
    end
  end
  def destroy
    @mood = Mood.find(params[:id])
    if @mood.delete
      flash[:notice] = "Mood deleted"
      redirect_to moods_path
    else
      flash[:alert] = "Mood failed to delete"
    end
  end
  private
  def mood_params
    params.require(:mood).permit(:time, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, url_for(:sort => column, :direction => direction, :page => nil), {:class => css_class, :remote => true}
  end
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/views/foods/_foods.html.erb
<table class="table table-striped">
  <th><%= sortable "time_consumed" %></th>
  <th><%= sortable "type_id", "Type of Meal" %></th>
  <th><%= sortable "category_id", "Food Category" %></th>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.time_consumed %></td>
      <td><%= food.type.name.titleize %></td>
      <td><%= food.category.name.titleize %></td>
    </tr>
  <% end %>
</table>
<%= will_paginate @foods, :remote => true %>

app/views/foods/index.html.erb
<div class="row">
  <h2 class="text-center">Foods you have logged</h1>
</div>
<div class="row">
  <div class="col-sm-offset-1 col-sm-10">
    <%= form_tag(foods_path, method: 'get', remote: true, class: "pull-right") do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <%= submit_tag('Search', :name => nil) %>
      </p>
      <%= hidden_field_tag :direction, params[:direction] %>
      <%= hidden_field_tag :sort, params[:sort] %>
    <% end %>
  </div>
</div>
<div class="row">
  <div class="col-sm-offset-1 col-sm-10" id="foods-display">
    <%= render 'foods' %>
  </div>
</div>

app/views/foods/index.js.erb
$('#foods-display').html("<%= j render "foods" %>")

app/views/foods/new.html.erb
<div class="row clearfix">
  <div class="col-sm-12 form_for_foods">
    <%= form_for @food do |f| %>
      <div class="form-group">
        <%= f.label "Category" %>
        <%= f.select("category_id", {:class => "category-select"}) do %>
          <% @categories.each do |category| %>
            <%= content_tag(:option, category.name, value: category.id) %>
          <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label "Meal Type" %>
        <%= f.select("type_id", {:class => "type-select"}) do %>
          <% @types.each do |type| %>
            <%= content_tag(:option, type.name, value: type.id) %>
          <% end %>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label "Time Consumed" %>
        <%= f.datetime_select :time_consumed%>
      </div>

      <%= f.submit :class => "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h3>Foods</h3>
<%= line_chart Food.group(:category_id).group_by_day(:time_consumed, last: 30).count %>

<h3>Moods</h3>
<%= line_chart Mood.group_by_day(:time, last: 30).minimum(:level) %>

<h3>Foods barchart</h3>
<%= bar_chart Food.group(:category_id).group_by_day(:time_consumed, last: 30).count %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FoodMood</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">FoodMood</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="active"><%= link_to "Home", root_path%></li>
            <li><%= link_to "Log New", new_food_path%></li>
            <li><%= link_to "Foods", foods_path%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>


              <li><%= link_to "Logout", destroy_user_session_path, :method => 'delete' %></li>
            <% else %>
              <li><%= link_to "Sign In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% end %>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container">
      <% if flash[:notice] %>
        <p class="alert alert-success"><%= flash[:notice] %></p>
      <% end %>
      <% if flash[:alert] %>
        <p class="alert alert-danger"><%= flash[:alert] %></p>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/moods/index.html.erb
<%= line_chart Mood.group_by_month(:time, last: 30).minimum(:level) %>

app/views/moods/new.html.erb
<div class="row clearfix">
  <div class="col-sm-12 form_for_foods">
    <%= form_for @mood do |f| %>

      <div class="form-group">
        <%= f.label "Time Consumed" %>
        <%= f.datetime_select :time%>
      </div>

      <div class="form-group">
        <%= f.label "Mood Level" %>
        <%= f.number_field :level, min:1, max:10%>
      </div>

      <%= f.submit :class => "btn btn-default" %>
    <% end %>
  </div>
</div>